version: 2
jobs:
  build:
    working_directory: ~/zipairlines-api
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install pip requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python3 manage.py test --settings=zipairlines.settings.circleci
      - store_artifacts:
          path: test-reports/
          destination: tr1
